# Generated by Django 4.2.1 on 2023-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128, unique=True)),
                ("connected_username", models.CharField(max_length=128, unique=True)),
                ("is_active", models.BooleanField(default=False, max_length=128)),
            ],
            options={"db_table": "connected_users",},
        ),
    ]
